language: node_js
services:
  - couchdb
sudo: false
node_js:
  - "5"
addons:
  firefox: "41.0.1"
script: npm run $COMMAND
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "npm install add-cors-to-couchdb"
  - "./node_modules/.bin/add-cors-to-couchdb"
env:
  matrix:
  - COMMAND=test
  - CLIENT=selenium:firefox:41.0.1 COMMAND=test
  - CLIENT=selenium:phantomjs COMMAND=test
  - COMMAND=coverage
branches:
  only:
  - master
